/* Generated by tools/generate_dma_protocol.py; do not edit. */
/* Source: mol_dma_protocol.json */
#ifndef MOL_DMA_PROTOCOL_H
#define MOL_DMA_PROTOCOL_H

#include <stdint.h>

#define MOL_DMA_MAGIC_REQUEST UINT32_C(0x4D4F4C51)
#define MOL_DMA_MAGIC_RESPONSE UINT32_C(0x4D4F4C52)
#define MOL_DMA_MAGIC_TRAILER UINT32_C(0x4D4F4C45)
#define MOL_DMA_VERSION UINT32_C(1)
#define MOL_DMA_BATCH_HEADER_WORDS UINT32_C(8)
#define MOL_DMA_TASK_HEADER_WORDS UINT32_C(8)
#define MOL_DMA_RESULT_HEADER_WORDS UINT32_C(8)
#define MOL_DMA_TRAILER_WORDS UINT32_C(8)
#define MOL_DMA_MAX_TASKS UINT32_C(64)
#define MOL_DMA_MAX_TRANSFER_BYTES UINT32_C(2097152)
#define MOL_DMA_MAX_TRANSFER_WORDS UINT32_C(524288)
#define MOL_DMA_MAX_ITEM_COUNT UINT32_C(64)
#define MOL_DMA_BATCH_FLAG_CONTINUE_ON_TASK_ERROR UINT32_C(1)
#define MOL_DMA_TASK_TANIMOTO UINT32_C(0)
#define MOL_DMA_TASK_GNN UINT32_C(1)
#define MOL_DMA_TASK_ADMET UINT32_C(2)
#define MOL_DMA_TASK_PIPELINE UINT32_C(3)
#define MOL_DMA_FLAG_FULL_GNN_OUTPUT UINT32_C(256)
#define MOL_DMA_FLAG_RETURN_INTERMEDIATE UINT32_C(512)
#define MOL_DMA_FLAG_SHARED_QUERY UINT32_C(1024)
#define MOL_DMA_STATUS_OK UINT32_C(0)
#define MOL_DMA_STATUS_BAD_MAGIC UINT32_C(1)
#define MOL_DMA_STATUS_BAD_VERSION UINT32_C(2)
#define MOL_DMA_STATUS_BAD_LENGTH UINT32_C(3)
#define MOL_DMA_STATUS_BAD_TASK UINT32_C(4)
#define MOL_DMA_STATUS_BAD_FLAGS UINT32_C(5)
#define MOL_DMA_STATUS_BAD_ITEM_COUNT UINT32_C(6)
#define MOL_DMA_STATUS_RESULT_OVERFLOW UINT32_C(7)
#define MOL_DMA_STATUS_TASK_TIMEOUT UINT32_C(8)
#define MOL_DMA_STATUS_LEGACY_BUSY UINT32_C(9)
#define MOL_DMA_STATUS_STREAM_TRUNCATED UINT32_C(10)
#define MOL_DMA_STATUS_INTERNAL_ERROR UINT32_C(11)
#define MOL_DMA_PAYLOAD_WORDS_FINGERPRINT UINT32_C(32)
#define MOL_DMA_PAYLOAD_WORDS_TANIMOTO_PAIR UINT32_C(64)
#define MOL_DMA_PAYLOAD_WORDS_GNN_ADJACENCY UINT32_C(79)
#define MOL_DMA_PAYLOAD_WORDS_GNN_FEATURES UINT32_C(1600)
#define MOL_DMA_PAYLOAD_WORDS_GNN_TOTAL UINT32_C(1679)
#define MOL_DMA_PAYLOAD_WORDS_ADMET_PER_ITEM UINT32_C(20)
#define MOL_DMA_PAYLOAD_WORDS_PIPELINE_TOTAL UINT32_C(1763)
#define MOL_DMA_PAYLOAD_WORDS_GNN_FULL_RESULT UINT32_C(3200)
#define MOL_DMA_PAYLOAD_WORDS_ADMET_RESULTS_PER_ITEM UINT32_C(4)
#define MOL_DMA_BATCH_MAGIC_WORD UINT32_C(0)
#define MOL_DMA_BATCH_VERSION_HEADER_WORDS_WORD UINT32_C(1)
#define MOL_DMA_BATCH_BATCH_ID_WORD UINT32_C(2)
#define MOL_DMA_BATCH_TASK_COUNT_WORD UINT32_C(3)
#define MOL_DMA_BATCH_TOTAL_WORDS_WORD UINT32_C(4)
#define MOL_DMA_BATCH_BATCH_FLAGS_WORD UINT32_C(5)
#define MOL_DMA_BATCH_MAX_RESULT_WORDS_WORD UINT32_C(6)
#define MOL_DMA_BATCH_RESERVED_WORD UINT32_C(7)
#define MOL_DMA_TASK_JOB_ID_WORD UINT32_C(0)
#define MOL_DMA_TASK_TASK_AND_FLAGS_WORD UINT32_C(1)
#define MOL_DMA_TASK_PAYLOAD_WORDS_WORD UINT32_C(2)
#define MOL_DMA_TASK_RESULT_CAPACITY_WORDS_WORD UINT32_C(3)
#define MOL_DMA_TASK_ITEM_COUNT_WORD UINT32_C(4)
#define MOL_DMA_TASK_USER_TAG_WORD UINT32_C(5)
#define MOL_DMA_TASK_TIMEOUT_CYCLES_WORD UINT32_C(6)
#define MOL_DMA_TASK_RESERVED_WORD UINT32_C(7)
#define MOL_DMA_RESPONSE_MAGIC_WORD UINT32_C(0)
#define MOL_DMA_RESPONSE_VERSION_HEADER_WORDS_WORD UINT32_C(1)
#define MOL_DMA_RESPONSE_BATCH_ID_WORD UINT32_C(2)
#define MOL_DMA_RESPONSE_EXPECTED_TASK_COUNT_WORD UINT32_C(3)
#define MOL_DMA_RESPONSE_HEADER_STATUS_WORD UINT32_C(4)
#define MOL_DMA_RESPONSE_OUTPUT_CAPACITY_WORDS_WORD UINT32_C(5)
#define MOL_DMA_RESPONSE_OUTPUT_FLAGS_WORD UINT32_C(6)
#define MOL_DMA_RESPONSE_RESERVED_WORD UINT32_C(7)
#define MOL_DMA_RESULT_JOB_ID_WORD UINT32_C(0)
#define MOL_DMA_RESULT_TASK_AND_STATUS_WORD UINT32_C(1)
#define MOL_DMA_RESULT_RESULT_WORDS_WORD UINT32_C(2)
#define MOL_DMA_RESULT_COMPUTE_CYCLES_LO_WORD UINT32_C(3)
#define MOL_DMA_RESULT_COMPUTE_CYCLES_HI_WORD UINT32_C(4)
#define MOL_DMA_RESULT_ITEM_COUNT_WORD UINT32_C(5)
#define MOL_DMA_RESULT_USER_TAG_WORD UINT32_C(6)
#define MOL_DMA_RESULT_DETAIL_WORD UINT32_C(7)
#define MOL_DMA_TRAILER_MAGIC_WORD UINT32_C(0)
#define MOL_DMA_TRAILER_BATCH_ID_WORD UINT32_C(1)
#define MOL_DMA_TRAILER_COMPLETED_COUNT_WORD UINT32_C(2)
#define MOL_DMA_TRAILER_ERROR_COUNT_WORD UINT32_C(3)
#define MOL_DMA_TRAILER_TOTAL_RESULT_WORDS_WORD UINT32_C(4)
#define MOL_DMA_TRAILER_BATCH_STATUS_WORD UINT32_C(5)
#define MOL_DMA_TRAILER_FIRST_ERROR_JOB_ID_WORD UINT32_C(6)
#define MOL_DMA_TRAILER_DETAIL_WORD UINT32_C(7)

typedef struct {
    uint32_t magic;
    uint32_t version_header_words;
    uint32_t batch_id;
    uint32_t task_count;
    uint32_t total_words;
    uint32_t batch_flags;
    uint32_t max_result_words;
    uint32_t reserved;
} mol_dma_batch_header_t;

typedef struct {
    uint32_t job_id;
    uint32_t task_and_flags;
    uint32_t payload_words;
    uint32_t result_capacity_words;
    uint32_t item_count;
    uint32_t user_tag;
    uint32_t timeout_cycles;
    uint32_t reserved;
} mol_dma_task_header_t;

typedef struct {
    uint32_t job_id;
    uint32_t task_and_status;
    uint32_t result_words;
    uint32_t compute_cycles_lo;
    uint32_t compute_cycles_hi;
    uint32_t item_count;
    uint32_t user_tag;
    uint32_t detail;
} mol_dma_result_header_t;

typedef struct {
    uint32_t magic;
    uint32_t batch_id;
    uint32_t completed_count;
    uint32_t error_count;
    uint32_t total_result_words;
    uint32_t batch_status;
    uint32_t first_error_job_id;
    uint32_t detail;
} mol_dma_trailer_t;

_Static_assert(sizeof(mol_dma_batch_header_t) == 32u, "mol_dma_batch_header_t must be eight words");
_Static_assert(sizeof(mol_dma_task_header_t) == 32u, "mol_dma_task_header_t must be eight words");
_Static_assert(sizeof(mol_dma_result_header_t) == 32u, "mol_dma_result_header_t must be eight words");
_Static_assert(sizeof(mol_dma_trailer_t) == 32u, "mol_dma_trailer_t must be eight words");

#endif
