#!/usr/bin/env python3
"""Generate shared Verilog and C constants for the MolRecommender DMA wire protocol."""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Mapping
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SPEC = ROOT / "protocol" / "mol_dma_protocol.json"
DEFAULT_VERILOG = ROOT / "rtl" / "mol_dma_protocol.vh"
DEFAULT_C = ROOT / "software" / "baremetal" / "src" / "mol_dma_protocol.h"


def parse_integer(value: int | str) -> int:
    if isinstance(value, int):
        return value
    return int(value, 0)


def upper(name: str) -> str:
    return name.upper().replace("-", "_")


def load_spec(path: Path) -> dict[str, object]:
    with path.open("r", encoding="utf-8") as source:
        spec = json.load(source)
    if spec.get("schema_version") != 1:
        raise ValueError("unsupported protocol schema_version")
    if spec.get("wire_endianness") != "little":
        raise ValueError("only little-endian wire format is supported")
    return spec


def protocol_constants(spec: Mapping[str, object]) -> list[tuple[str, int, bool]]:
    constants: list[tuple[str, int, bool]] = []

    magic = spec["magic"]
    assert isinstance(magic, Mapping)
    for name in ("request", "response", "trailer"):
        constants.append((f"MAGIC_{upper(name)}", parse_integer(magic[name]), True))

    constants.append(("VERSION", parse_integer(spec["version"]), False))

    section_prefixes = (
        ("headers", "", {"batch_words": "BATCH_HEADER_WORDS", "task_words": "TASK_HEADER_WORDS", "result_words": "RESULT_HEADER_WORDS", "trailer_words": "TRAILER_WORDS"}),
        ("limits", "", {}),
        ("batch_flags", "BATCH_FLAG_", {}),
        ("task_ids", "TASK_", {}),
        ("task_flags", "FLAG_", {}),
        ("statuses", "STATUS_", {}),
        ("payload_words", "PAYLOAD_WORDS_", {}),
    )
    for section_name, prefix, aliases in section_prefixes:
        section = spec[section_name]
        assert isinstance(section, Mapping)
        for name, value in section.items():
            macro = aliases.get(name, f"{prefix}{upper(name)}")
            constants.append((macro, parse_integer(value), False))

    offsets = spec["field_offsets"]
    assert isinstance(offsets, Mapping)
    for header_name, fields in offsets.items():
        assert isinstance(fields, Mapping)
        for field_name, value in fields.items():
            constants.append(
                (f"{upper(header_name)}_{upper(field_name)}_WORD", parse_integer(value), False)
            )
    return constants


def validate_spec(spec: Mapping[str, object], constants: list[tuple[str, int, bool]]) -> None:
    names = [name for name, _, _ in constants]
    if len(names) != len(set(names)):
        raise ValueError("protocol contains duplicate generated constant names")

    headers = spec["headers"]
    assert isinstance(headers, Mapping)
    if any(parse_integer(value) != 8 for value in headers.values()):
        raise ValueError("protocol version 1 requires eight-word headers")

    task_ids = spec["task_ids"]
    statuses = spec["statuses"]
    assert isinstance(task_ids, Mapping) and isinstance(statuses, Mapping)
    task_values = {parse_integer(value) for value in task_ids.values()}
    if task_values != {0, 1, 2, 3, 0xFE}:
        raise ValueError("task IDs must be 0..3 plus weight reload 0xFE")
    if sorted(parse_integer(value) for value in statuses.values()) != list(range(12)):
        raise ValueError("status codes must be the contiguous range 0..11")


def verilog_literal(value: int, hexadecimal: bool) -> str:
    return f"32'h{value:08X}" if hexadecimal else str(value)


def c_literal(value: int, hexadecimal: bool) -> str:
    return f"UINT32_C(0x{value:08X})" if hexadecimal else f"UINT32_C({value})"


def render_verilog(constants: list[tuple[str, int, bool]], source_name: str) -> str:
    lines = [
        "// Generated by tools/generate_dma_protocol.py; do not edit.",
        f"// Source: {source_name}",
        "`ifndef MOL_DMA_PROTOCOL_VH",
        "`define MOL_DMA_PROTOCOL_VH",
        "",
    ]
    lines.extend(
        f"`define MOL_DMA_{name} {verilog_literal(value, hexadecimal)}"
        for name, value, hexadecimal in constants
    )
    lines.extend(("", "`endif", ""))
    return "\n".join(lines)


STRUCTS = (
    (
        "mol_dma_batch_header_t",
        ("magic", "version_header_words", "batch_id", "task_count", "total_words", "batch_flags", "max_result_words", "reserved"),
    ),
    (
        "mol_dma_task_header_t",
        ("job_id", "task_and_flags", "payload_words", "result_capacity_words", "item_count", "user_tag", "timeout_cycles", "reserved"),
    ),
    (
        "mol_dma_result_header_t",
        ("job_id", "task_and_status", "result_words", "compute_cycles_lo", "compute_cycles_hi", "item_count", "user_tag", "detail"),
    ),
    (
        "mol_dma_trailer_t",
        ("magic", "batch_id", "completed_count", "error_count", "total_result_words", "batch_status", "first_error_job_id", "detail"),
    ),
)


def render_c(constants: list[tuple[str, int, bool]], source_name: str) -> str:
    lines = [
        "/* Generated by tools/generate_dma_protocol.py; do not edit. */",
        f"/* Source: {source_name} */",
        "#ifndef MOL_DMA_PROTOCOL_H",
        "#define MOL_DMA_PROTOCOL_H",
        "",
        "#include <stdint.h>",
        "",
    ]
    lines.extend(
        f"#define MOL_DMA_{name} {c_literal(value, hexadecimal)}"
        for name, value, hexadecimal in constants
    )
    lines.append("")
    for struct_name, fields in STRUCTS:
        lines.append("typedef struct {")
        lines.extend(f"    uint32_t {field};" for field in fields)
        lines.append(f"}} {struct_name};")
        lines.append("")
    for struct_name, _ in STRUCTS:
        lines.append(
            f'_Static_assert(sizeof({struct_name}) == 32u, "{struct_name} must be eight words");'
        )
    lines.extend(("", "#endif", ""))
    return "\n".join(lines)


def update_or_check(path: Path, expected: str, check: bool) -> bool:
    if check:
        actual = path.read_text(encoding="utf-8") if path.exists() else ""
        if actual != expected:
            print(f"out of date: {path}")
            return False
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as output:
        output.write(expected)
    print(f"generated: {path}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--spec", type=Path, default=DEFAULT_SPEC)
    parser.add_argument("--verilog-out", type=Path, default=DEFAULT_VERILOG)
    parser.add_argument("--c-out", type=Path, default=DEFAULT_C)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    try:
        spec = load_spec(args.spec)
        constants = protocol_constants(spec)
        validate_spec(spec, constants)
    except (OSError, ValueError, KeyError, TypeError, json.JSONDecodeError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    source_name = args.spec.name
    verilog = render_verilog(constants, source_name)
    c_header = render_c(constants, source_name)
    results = (
        update_or_check(args.verilog_out, verilog, args.check),
        update_or_check(args.c_out, c_header, args.check),
    )
    return 0 if all(results) else 1


if __name__ == "__main__":
    raise SystemExit(main())
